[package]
name = "krnl"
version = "0.0.1"
authors = ["Charles R Earp <charles.r.earp@gmail.com>"]
edition = "2021"
homepage = "https://github.com/charles-r-earp/krnl"
keywords = ["kernel", "compute", "vulkan", "gpu"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/charles-r-earp/krnl"
publish = false

[workspace]
members = ["benchmarks/*"]

[dependencies]
krnl-macros = { path = "krnl-macros" }
krnl-core = { path = "krnl-core" }
vulkano = { git = "https://github.com/vulkano-rs/vulkano", branch = "0.32.X", optional = true }
serde = { version = "1.0.143", default-features = false, features = ["derive", "rc"] }
spirv = { version = "0.2.0", default-features = false, features = ["serialize", "deserialize"] }
thiserror = "1.0.31"
derive_more = "0.99.11"
paste = "1.0.7"
num-traits = "0.2.14"
half = { git = "https://github.com/starkat99/half-rs", default-features = false, features = ["num-traits"] }
once_cell = { version = "1.13.0", default-features = false, features = ["std", "alloc"] }
parking_lot = "0.12.1"
anyhow = "1.0.60"
crossbeam-channel = { version = "0.5.6", optional = true }
futures-util = { version = "0.3.21", default-features = false }
blocker = { version = "0.1.2", features = ["thread_yield"] }
futures-lite = { version = "1.12.0", optional = true, default-features = false }
bytemuck = { version = "1.11.0", default-features = false }
bincode = "1.3.3"
dashmap = { version = "5.3.4", optional = true }
rspirv = "0.11.0"
dry = "0.1.1"
ash = { version = "0.37.1", optional = true }

[target."cfg(any(target_os = \"ios\", target_os = \"macos\"))".dependencies]
ash-molten = { version = "0.12.0", features = ["pre-built"], optional = true }

[features]
# TODO change device to vulkan?
device = ["dep:vulkano", "dep:ash", "dep:ash-molten", "dep:crossbeam-channel", "dep:futures-lite", "dep:dashmap"]

[[test]]
name = "integration_tests"
path = "tests/integration_tests.rs"
harness = false

[dev-dependencies]
libtest-mimic = "0.6.0"
