[package]
name = "test-device"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["dylib"]

[dependencies]
krnl-core = { path = "../../../../krnl-core" }
spirv-std = { git = "https://github.com/EmbarkStudios/rust-gpu" }
