[package]
name = "xtask"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true
publish = false
autoexamples = false
autotests = false
autobenches = false

[dependencies]
clap.workspace = true
poloto = "18.0.6"
serde_json = "1.0.95"

