[package]
name = "shader"
version = "0.1.0"
edition = "2021"
publish = false 

[lib]
crate-type = ["dylib"]

[workspace]

[dependencies]
glam = { version = "0.23.0", default-features = false, features = ["libm"] }
spirv-std = "0.6.1"
