[package]
name = "shader-builder"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
spirv-builder = { version = "0.6.1", default-features = false, features = ["use-installed-tools"] }
