
name: Continuous Integration

on:
  push:
    branches: 
      - main 
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
      CARGO_INCREMENTAL: 0
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
#          - os: windows-latest
#            target: x86_64-pc-windows-msvc
#          - os: macos-latest
#            target: x86_64-apple-darwin
    steps:
    - uses: actions/checkout@v2
#    - name: build
#      run: cargo build -v
#    - name: test
#      run: cargo test --no-default-features -p krnl -p krnlc-tests -v -- --format=terse
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2023-01-21
        override: true
        components: rust-src rustc-dev llvm-tools-preview
    - name: krnlc check 
      run: cargo run --manifest-path krnlc/Cargo.toml -- --check -p krnl -p krnlc tests -p compute-benchmarks

#  lint: 
#    runs-on: ubuntu-latest
#    env:
#      RUST_BACKTRACE: 1
#      CARGO_INCREMENTAL: 0
#    steps:
#    - uses: actions/checkout@v2
#    - name: lint
#      run: cargo xtask lint -v

# cargo-deny:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: EmbarkStudios/cargo-deny-action@v1
#      - uses: EmbarkStudios/cargo-deny-action@v1
#        with:
#          arguments: --manifest-path crates/krnlc/Cargo.toml
